### ISSUE TITLE
dos x86 int 0x21 and stack operations wrongly decompiled

### ISSUE THREAD

**Issue by xor2003** [uxmal/reko#282]
1. int 0x21 become syscall 0x33
2. ax argument is not indicated in the decompilation.
3. bl is not an argument.

Listing:

```
  16028     7521             proc        setmemallocstrat near   ; CODE XREF: deinit_125B9+15p
  16029                                      ; sub_12D35+22p ...
  16030     7521  50                     push    ax
  16031     7522  0F B6 D8               movzx   bx, al
  16032     7525  B8 5801                mov     ax, 5801h
  16033     7528  CD 21                  int     21h         ; DOS - 3+ - GET/SET MEMORY ALLOCATION STRATEGY
  16034                                      ; AL = function code: set allocation strategy
  16035     752A  5B                     pop     bx
  16036     752B  C1 EB 08                       shr     bx, 8
  16037     752E  B8 5803                mov     ax, 5803h
  16038     7531  CD 21                  int     21h         ; DOS - 3+ - GET/SET MEMORY ALLOCATION STRATEGY
  16039                                      ; AL = function code: (DOS 5beta) set UMB link state
  16040     7533  C3                     retn
  16041     7534             endp        setmemallocstrat
```

Decompiled to:

```
byte setmemallocstrat(word16 ax, byte bl)
// stackDelta: 0; fpuStackDelta: 0; fpuMaxParam: -1

// MayUse:  ax bl
// LiveOut: al
// Trashed: SCZO ah al ax bh bl bx eax ebx rax rbx
// Preserved: sp
setmemallocstrat_entry:
// DataOut: ax bl ds ss
// DataOut (flags): 
// SymbolicIn: sp:fp
// LocalsOut: fp(16)

l0800_7521:
    msdos_set_memory_allocation_strategy(bl)
    **__syscall(0x21)**
    return 0x03
// DataOut: al ds ss
// DataOut (flags): 
// SymbolicIn: sp:fp

setmemallocstrat_exit:
// DataOut: al
// DataOut (flags): 
// SymbolicIn: sp:fp bx:ax >>u 0x0008 ax:0x5803 -2(fp):ax

byte setmemallocstrat(**word16 ax**, **byte bl**)
{
    msdos_set_memory_allocation_strategy(bl);
    **__syscall(33);**
    return 0x03;
}
```

**Comment by uxmal** [comment]
Wow,  good catch. I guess I have a few things to work on on Tuesday!

**Comment by ptomin** [comment]
0x21 is the same as 33. Is not it?

**Comment by uxmal** [comment]
The second int 21h should have been resolved as the first one. Probably a missing entry in realmodeintservices.xml

**Comment by xor2003** [comment]
Yes, 0x21=33 thanks. (The binary is in another case.)

**Comment by xor2003** [comment]
I have partially fixed it (please check):
  <service name="msdos_get_UMB_link_state">
	<syscallinfo>
	  <vector>21</vector>
	  <regvalue reg="ah">58</regvalue>
	  <regvalue reg="al">02</regvalue>
	</syscallinfo>
	<signature>
	  <return>
		<flag>C</flag>
		<reg>al</reg>
	  </return>
	</signature>
  </service>
  <service name="msdos_set_UMB_link_state">
	<syscallinfo>
	  <vector>21</vector>
	  <regvalue reg="ah">58</regvalue>
	  <regvalue reg="al">03</regvalue>
	</syscallinfo>
	<signature>
	  <return>
		<flag>C</flag>
		<reg>ax</reg>
	  </return>
	  <arg>
		<reg>bx</reg>
	  </arg>
	</signature>
  </service>

Now:
﻿byte setmemallocstrat(word16 ax, byte bl)
{
    msdos_set_memory_allocation_strategy(bl);
    msdos_set_UMB_link_state(ax >>u 0x08);
    return 0x03;
}
But I think it should be:
﻿byte setmemallocstrat(word16 ax)
{
    msdos_set_memory_allocation_strategy(al);
    msdos_set_UMB_link_state(ax >>u 0x08);
    return 0x03;
}
Maybe it is because of movzx...

**Comment by uxmal** [comment]
I don't have my ms-dos manuals with me but your fix looks fine. Register propagation is obviously not working so leave this issue open so I can look at it on Tuesday.  Perhaps you could submit a pull request with your fix of realmodeintservices.xml?

**Comment by ptomin** [comment]
```
<return>
        <flag>C</flag>
        <reg>ax</reg>
</return>
```
It is incorrect syntax. Is not it, John?

**Comment by uxmal** [comment]
Yes Pavel I was rushed.  The AX returned from the service will need an out argument:
```xml
<arg out="true">
     <reg>ax </reg>
</arg>
```

**Comment by uxmal** [comment]
`bl` is no longer live-in. There's still a bug that needs to be fixing: I'm seeing
```c
byte setmemallocstrat(word16 ax)
{
    msdos_set_memory_allocation_strategy((byte) (word16) al);
    msdos_set_UMB_link_state(ax >>u 0x08);
    return 0x03;
}    
```
which is wrong of course; it should be:
```c
   msdos_set_memory_allocation_strategy((byte) ax);
```

**Comment by uxmal** [comment]
...and that bug will have to wait until the `analysis-development` branch is stable enough to be merged into the master. This will take a couple of weeks; I'm still working on some stubborn issues on that branch. I will keep this issue open until then.

**Comment by uxmal** [comment]
For those who want to know the cause of the bug above: the `Alias` class is supposed to expand the `ax` parameter into an aliased assignment `al = (byte) ax`, but doesn't. The new SSA transform being developed in the `analysis-development` branch does this expansion correctly.

**Comment by uxmal** [comment]
As mentioned the `analysis-development` handles this.
